//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moon.Mvc {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FluentValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentValidationResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
        		 
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moon.Mvc.FluentLocal.FluentValidationResource", typeof(FluentValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 是一个不合法的信用卡号。 的本地化字符串。
        /// </summary>
        public static string CreditCardError {
            get {
                return ResourceManager.GetString("CreditCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 是一个不合法的电子邮件地址。 的本地化字符串。
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 应该和 &apos;{PropertyValue}&apos; 相等。 的本地化字符串。
        /// </summary>
        public static string equal_error {
            get {
                return ResourceManager.GetString("equal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须是 {MaxLength} 字符长度，你已经输入了 {TotalLength} 字符。 的本地化字符串。
        /// </summary>
        public static string exact_length_error {
            get {
                return ResourceManager.GetString("exact_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须在 {From} 和 {To} (排除)之间， 你输入了 {Value}。 的本地化字符串。
        /// </summary>
        public static string exclusivebetween_error {
            get {
                return ResourceManager.GetString("exclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须大于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string greaterthan_error {
            get {
                return ResourceManager.GetString("greaterthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须大于或等于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string greaterthanorequal_error {
            get {
                return ResourceManager.GetString("greaterthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须在 {From} 和 {To} 之间， 你输入了 {Value}。 的本地化字符串。
        /// </summary>
        public static string inclusivebetween_error {
            get {
                return ResourceManager.GetString("inclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须在 {MinLength} 到 {MaxLength} 字符，你已经输入了 {TotalLength} 字符。 的本地化字符串。
        /// </summary>
        public static string length_error {
            get {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须小于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string lessthan_error {
            get {
                return ResourceManager.GetString("lessthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须小于或等于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string lessthanorequal_error {
            get {
                return ResourceManager.GetString("lessthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 的长度必须大于 0。 的本地化字符串。
        /// </summary>
        public static string notempty_error {
            get {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不能和 &apos;{PropertyValue}&apos; 相等。 的本地化字符串。
        /// </summary>
        public static string notequal_error {
            get {
                return ResourceManager.GetString("notequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不能为空。 的本地化字符串。
        /// </summary>
        public static string notnull_error {
            get {
                return ResourceManager.GetString("notnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的条件不符合 &apos;{PropertyName}&apos;。 的本地化字符串。
        /// </summary>
        public static string predicate_error {
            get {
                return ResourceManager.GetString("predicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 的格式不正确。 的本地化字符串。
        /// </summary>
        public static string regex_error {
            get {
                return ResourceManager.GetString("regex_error", resourceCulture);
            }
        }
    }
}
